Ws2 1823
ASUWebPlatforms/webspark-ci pull request #205
Opened 2023-11-01 14:17 UTC by Bob-E

### Description of problem:
UDS form styles display on admin-facing forms. Admin-facing forms should use the Admin theme.

### Solution:
The final solution was to modify form.inc to not add `uds-form` class to all forms, but to add the class only to webform forms via a webform template override.

### Links
- [JIRA ticket](https://asudev.jira.com/browse/WS2-1823)

### Checklist

- [x] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [x] Solution is documented on the Jira ticket
- [x] QA steps to verify have been included on the Jira ticket
- [x] No new PHP or JS errors
- [x] No accessibility issues are introduced with this update
- [x] Added/updated README.md files, if relevant

### Verified in browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

2023-11-01 14:25 UTC, mlsamuelson commented
[![Visit Site](https://raw.githubusercontent.com/pantheon-systems/terminus-build-tools-plugin/master/assets/images/visit-site-36.png)](https://pr-205-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-205](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-205) for webspark-ci.

2023-11-01 21:16 UTC, Bob-E commented
waiting for UDS update for valid form fields CSS (overriding bootstrap) to take this PR out of draft

2023-11-08 21:46 UTC, mlsamuelson requested changes
@Bob-E Initial testing indicates this is a sound approach which will lend us flexibility moving forward. A few regressions to the admin forms need to be addressed now that they're not benefiting from the UDS styles:

* Required marks in admin forms look "off". 
* Checkboxes are misaligned. (Maybe check if radios are, too.)
* Field has two focus states. Ideally, we'd keep the UDS black outline and unset the other.

![Screenshot 2023-11-08 at 2 41 22 PM](https://github.com/ASUWebPlatforms/webspark-ci/assets/212131/21d95cd1-a1a0-4798-992f-fa968597a86b)

2024-04-15 20:53 UTC, mlsamuelson approved these changes

2024-04-15 20:53 UTC, merged