Ws2 2002
ASUWebPlatforms/webspark-ci pull request #400
Opened 2024-04-17 16:48 UTC by tbutterf

### Description

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-0000)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

2024-04-17 17:08 UTC, mlsamuelson commented
[![Visit Site](https://raw.githubusercontent.com/pantheon-systems/terminus-build-tools-plugin/master/assets/images/visit-site-36.png)](https://pr-400-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-400](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-400) for webspark-ci.

2024-04-26 20:57 UTC, mlsamuelson requested changes
This looks really great and tests out well.

One thing I found is that the `Icon List Maroon` and `Icon List Gray 7 Gold` list properties don't style correctly on newly added icons. To see this in the PR environment, go to https://pr-400-webspark-ci.ws.asu.edu/node/60/edit and change the list properties style on the icon list to either of the options I noted and see that only the last 2 icons change color - these were the original icons which haven't been deleted and re-inserted. Looks like there's different classes in place on the old and new icons, so perhaps we just need some style rules to account for both.

2024-04-26 21:30 UTC, tbutterf commented
Ah. Yes, I didn't test the colors thoroughly. Thanks for catching that. It makes sense that they might have gotten messed up with the changes that I made. I will address this and push up the change.

2024-04-30 21:46 UTC, mlsamuelson approved these changes

2024-04-30 21:46 UTC, merged