add js to hide filters
ASUWebPlatforms/webspark-ci pull request #456
Opened 2024-06-07 00:48 UTC by tbutterf

### Description

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-0000)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant
- [ ] Confirm that any yaml files included have a matching update hook

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

2024-06-07 00:55 UTC, mlsamuelson commented
[![Visit Site](https://raw.githubusercontent.com/pantheon-systems/terminus-build-tools-plugin/master/assets/images/visit-site-36.png)](https://pr-456-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-456](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-456) for webspark-ci.

2024-06-07 22:10 UTC, mlsamuelson requested changes
See my comment on setTimeout. I tested the idea wit this prompt in ChatGPT and found the results helpful:
```
I am writing javascript and I want to improve my code. Instead of using setTimeout() to wait for a page element to load before I execute my code, I want to use async / await. Can you share examples?
```
It suggested a mutation observer as an alternative, and that could be a good option, too.

Also, in testing this update, I noted that when the filters are hidden, the values in them are not zeroed out. The Filter by title gets zeroed on submit, since I believe values on disabled fields are ignored, but the other filters are tied to JS that syncs their values into hidden fields, and those values are retained.  the potential for user confusion is high.  I'm thinking that when the filter fields are hidden, we should zero them out in both the visible and hidden fields. No need to retain settings if the user switches the sort back. In that case, the user will at least be able to see the settings were lost and they can avoid saving the form and reload the page and get their settings back.

Happy to talk this through if you have questions.

2024-06-11 23:00 UTC, tbutterf commented
@mlsamuelson I think this is ready for review again.

2024-06-14 16:19 UTC, mlsamuelson approved these changes

2024-06-14 16:26 UTC, merged