WS2-2070: Fixing anchor color for ckeditor (change it to maroon).
ASUWebPlatforms/webspark-ci pull request #458
Opened 2024-06-10 17:18 UTC by igardunoasu

### Description

The visual editor in the body displays hyperlinks as blue.

Create a new css rule to override the hyperlink color.
### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-2070)

### Checklist

- [x] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [x] Solution is documented on the Jira ticket
- [x] QA steps to verify have been included on the Jira ticket
- [x] No new PHP or JS errors
- [x] No accessibility issues are introduced with this update

### Verified in browsers 

- [x] Chrome
- [x] Safari
- [x] Firefox
- [ ] Edge

### Screenshots

![maroonhyperlink](https://github.com/ASUWebPlatforms/webspark-ci/assets/99989701/10509719-06b1-46e5-9c1e-b35b54541e88)

Note: Sections that are not applicable for this issue can be removed.

2024-06-10 17:26 UTC, mlsamuelson commented
[![Visit Site](https://raw.githubusercontent.com/pantheon-systems/terminus-build-tools-plugin/master/assets/images/visit-site-36.png)](https://pr-458-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-458](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-458) for webspark-ci.

2024-06-12 18:19 UTC, tbutterf requested changes
This looks good, but I think it is too narrowly scoped. I think it should be sufficient to do 
```
.ck a, .ck a:hover {
  color: rgba(var(--bs-link-color-rgb), var(--bs-link-opacity, 1));
}
```

2024-06-14 16:21 UTC, igardunoasu commented
@tbutterf Hi, the change was applied.

2024-06-14 20:42 UTC, tbutterf approved these changes

2024-06-14 20:42 UTC, merged