WS2-2154: Update People Results in the Webdir admin UI
ASUWebPlatforms/webspark-ci pull request #528
Opened 2024-07-22 18:32 UTC by tbutterf

### Description

The big work for this ticket has to be done in SCHWEB. It is in [SCHWEB-1275](https://asudev.jira.com/browse/SCHWEB-1275). This pull request only fixes the logic to remove the extra commas if no display name, title, or department is provided. This will make for a more sustainable interface, regardless of whether some data exists for display.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-0000)

### Checklist

- [x] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [x] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [x] No new PHP or JS errors
- [x] No accessibility issues are introduced with this update
- [x] Added/updated README.md files, if relevant
- [x] Confirm that any yaml files included have a matching update hook

### Verified in browsers 

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

2024-07-22 18:41 UTC, mlsamuelson commented
[![Visit Site](https://raw.githubusercontent.com/pantheon-systems/terminus-build-tools-plugin/master/assets/images/visit-site-36.png)](https://pr-528-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-528](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-528) for webspark-ci.

2024-08-06 15:48 UTC, mlsamuelson requested changes
In testing this, I never see anything but ASURITE and Name, even when there should be more...
![Screenshot 2024-08-06 at 8 47 51 AM](https://github.com/user-attachments/assets/4a2a4a89-42af-402b-9eb0-56aa6372e803)

2024-08-06 15:50 UTC, mlsamuelson reviewed
Never mind that - I see that's because https://asudev.jira.com/browse/SCHWEB-1275 still needs to be implemented.

2024-08-08 16:04 UTC, tbutterf commented
This is ready for re-review.

2024-08-08 22:24 UTC, mlsamuelson approved these changes

2024-08-08 22:51 UTC, chill5-0 approved these changes
This is working in the multidev - approved.

2024-08-12 15:34 UTC, merged