WS2-2194: Changed banners.twig, button-cta.twig, field--block-content-field-heading.html.twig and heading.twig for accessibility
ASUWebPlatforms/webspark-ci pull request #531
Opened 2024-07-23 14:39 UTC by juanmitriatti

### Description

#### Solution 
Changed banners.twig, button-cta.twig, field--block-content-field-heading.html.twig and heading.twig for accessibility

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-2194)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant
- [ ] Confirm that any yaml files included have a matching update hook

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

2024-08-05 21:53 UTC, mlsamuelson requested changes
@juanmitriatti The heading sizing is off in the banner on https://pr-531-webspark-ci.ws.asu.edu/kitchen-sink after this update. I assume this depends on the `unity-bootstrap-theme` styles being updated. Does the release with those updates need to be included with this PR?

2024-08-08 20:15 UTC, tbutterf requested changes
Just one thing that I think needs to be fixed. Otherwise, looks good.

2024-08-09 17:35 UTC, juanmitriatti commented on web/themes/webspark/renovation/templates/field/field--block-content--field-heading.html.twig
> +      html_tag : 'h1',
@tbutterf  this is now ready. 
Thanks for your feedback.

2024-08-09 17:48 UTC, tbutterf approved these changes

2024-08-09 18:09 UTC, juanmitriatti commented
> need to be included with this PR?

Hi @mlsamuelson 
It depends on the` unity-bootstrap-theme`. This is the PR associated on the UDS side : https://github.com/ASU/asu-unity-stack/pull/1330/files . It needs to be included.
Note : Yesterday. I did the upgrade from the unity boostrap theme.
Thanks

2024-08-12 15:44 UTC, mlsamuelson approved these changes

2024-08-12 15:44 UTC, merged