WS2-2089: New Component: Animated Quote
ASUWebPlatforms/webspark-ci pull request #570
Opened 2024-09-02 20:19 UTC by juanmitriatti

### Description
New Component: Animated Quote

#### Solution 
Added new plugin with animated option for ckeditor
![ckeditorAnimated](https://github.com/user-attachments/assets/f7c8021d-eb3d-41f5-bdfd-db0dc75129b6)

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-2089)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant
- [ ] Confirm that any yaml files included have a matching update hook

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

2024-09-02 20:27 UTC, mlsamuelson commented
[![Visit Site](https://raw.githubusercontent.com/pantheon-systems/terminus-build-tools-plugin/master/assets/images/visit-site-36.png)](https://pr-570-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-570](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-570) for webspark-ci.

2024-09-03 20:27 UTC, mlsamuelson reviewed
Notes from our Zoom discussion:
* Next step is to create a story for the Animated Quote component in the `unity-bootstrap-theme` component in UDS (for UDS-1758) to serve as the reference story for this component,
* Then rework this PR and implement that story as an Animated Quote plugin in CKEditor that has the following features:
  * an icon to add Animated Quote
  * an icon to highlight text. It should be disabled unless the focus is in an Animated Quote. In the future we could have the option to make this usable in other components, but for now let's limit it to this one.
  * the highlight colors should be limited to what's in the mockup.

2024-09-18 23:05 UTC, mlsamuelson requested changes
There is a merge conflict to resolve.

Can we please locate the two buttons so they are side-by-side? Can the animated blockquote button be first, and then the highlight button right after it? This will improve the UX.

Also, I've noticed when you make a link in the new quote in the editor, that the link is maroon instead of black.  I think that was an issue some of the other plugins had. When you save and view the rendered output, the link is the correct (black) color. Hopefully that's an easy fix.

2024-09-18 23:44 UTC, mlsamuelson requested changes

2024-09-18 23:44 UTC, mlsamuelson commented on web/modules/webspark/webspark_ckeditor_plugins/js/ckeditor5_plugins/websparkPlugin/src/animatedtext/css/animatedtext.css
Let's redo this file so it only includes the styles we're using, and it also should not include another project's copyright.

2024-09-18 23:44 UTC, mlsamuelson commented on web/modules/webspark/webspark_ckeditor_plugins/js/ckeditor5_plugins/websparkPlugin/src/animatedtext/websparkanimatedtextui.js
> +      "Green pen": t("Green pen"),
Can we remove the unused options?

2024-09-18 23:44 UTC, mlsamuelson commented on web/themes/webspark/renovation/src/sass/helpers/_ckeditor.scss
We can remove the non-yellow color declarations from this file.

2024-09-19 00:12 UTC, tbutterf commented
@juanmitriatti I have followed the QA steps, and the plugin buttons do not appear by default on a new install. I have attempted several clean installs, and the buttons are not added by default. They are available to be added by an administrator, but they are not appearing by default. I think maybe you need to import some configs so that they appear by default.

2024-09-19 00:38 UTC, tbutterf commented
Also, not everyone is going to want to have a "Title" for their block quote. However, if I leave that field blank, the space reserved for it does not go away. It would be good to have it so that if a field is not used, the space it would have taken up should be removed.

2024-09-19 00:39 UTC, tbutterf commented
One last thing. On the clean install I attempted, I went in and added the two buttons as a site admin. Afterwards, when I tried to use it, the highlight did not animate. It looks like this:
<img width="309" alt="image" src="https://github.com/user-attachments/assets/1ba08274-c23b-4553-9654-f0e628b11fe9">

2024-09-19 00:44 UTC, tbutterf commented
There's a problem with tabbed browsing order. When you are in the "Title" field, if you tab to go to the "Content" field, it skips over that field entirely and goes to "Citation name" instead.

2024-09-19 15:49 UTC, juanmitriatti commented
All the issues reported were addressed. Please review again.
CC @mlsamuelson  @tbutterf

2024-09-19 15:49 UTC, juanmitriatti commented on web/themes/webspark/renovation/src/sass/helpers/_ckeditor.scss
Fixed, please review again.

2024-09-19 15:49 UTC, juanmitriatti commented
> Also, not everyone is going to want to have a "Title" for their block quote. However, if I leave that field blank, the h4 space reserved for it does not go away. It should be that if a field is not used, the space it would have taken up should not be included in the markup. <img alt="image" width="469" src="https://private-user-images.githubusercontent.com/6109406/368795121-5a100646-31a8-4254-a5ad-804c93d8a87a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjEyNzAsIm5iZiI6MTcyNjc2MDk3MCwicGF0aCI6Ii82MTA5NDA2LzM2ODc5NTEyMS01YTEwMDY0Ni0zMWE4LTQyNTQtYTVhZC04MDRjOTNkOGE4N2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMTU0OTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTk1Mzk4YmZkZTAzOTU0Y2I5YThiZWRlYTY5YjIyYTA1NDU1ZWM2MGNlOWI4MDY3MGJkYmYxMDBiODI4YWUxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.x-AoyxCI-l-L83AdADkFRzLSmejbSnBTX_XTKZhH710">

Fixed, please review again.

2024-09-19 20:35 UTC, mlsamuelson commented
Still seeing the issue with Content textarea not being focusable.
Also there is a regression with the styles not displaying in the Edit and View modes.
![view-basic-page](https://github.com/user-attachments/assets/c5bd10ff-c155-4e71-b17a-49e7c4bdb267)
![editor-basic-and-full-html](https://github.com/user-attachments/assets/363c864a-0cee-4194-87ab-e3266a5d1c64)

2024-09-19 20:38 UTC, mlsamuelson commented
It seems the content textarea isn't focusable in the other plugins as well. And in the Buttons plugin the selection fields aren't focusable. Hopefully that can be fixed for all of these.

2024-09-19 20:41 UTC, mlsamuelson commented
My bad. I had not run the `yarn production` command to rebuild the theme so the styles weren't showing.

So that's not an issue.

2024-09-23 19:44 UTC, mlsamuelson approved these changes

2024-09-23 19:47 UTC, merged