WS2-2297: All Custom Blocks: H1 heading text is focusable, but shouldn't be
ASUWebPlatforms/webspark-ci pull request #615
Opened 2024-10-18 11:33 UTC by juanmitriatti

### Description

#### Solution 
Added a condition to remove `tabindex="0"` from `<h1>` headings.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/WS2-2297)

### Checklist

- [ ] Design updates match [Web Standards](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/) and [Unity Design System](https://unity.web.asu.edu)
- [ ] Solution is documented on the Jira ticket
- [ ] QA steps to verify have been included on the Jira ticket
- [ ] No new PHP or JS errors
- [ ] No accessibility issues are introduced with this update
- [ ] Added/updated README.md files, if relevant
- [ ] Confirm that any yaml files included have a matching update hook

### Verified in browsers 

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Screenshots

Note: Sections that are not applicable for this issue can be removed.

2024-10-18 11:41 UTC, mlsamuelson commented
[![Visit Site](https://raw.githubusercontent.com/pantheon-systems/terminus-build-tools-plugin/master/assets/images/visit-site-36.png)](https://pr-615-webspark-ci.pantheonsite.io/)

Created multidev environment [pr-615](https://dashboard.pantheon.io/sites/aec2f75f-35eb-41f8-abe7-95b292415259#pr-615) for webspark-ci.

2024-10-22 16:41 UTC, tbutterf requested changes
This only prevents H1 tags from being focusable, but we need to also make sure other heading tags aren't focusable. I wonder if we shouldn't take a different approach. Perhaps we could create an array of html tags that should or should not be focusable, and then use that array in our logic as to whether we include the tabindex attribute.

2024-10-22 16:41 UTC, tbutterf commented
@mlsamuelson I'd like your opinion on my review, if possible. Thanks!

2024-10-22 19:12 UTC, mlsamuelson commented
@tbutterf I think we can approach it with a simpler fix. 

The template targeted is the heading template... headings by themselves should not be focusable since they cannot be interacted with (see https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Keyboard: "If an element can be focused using the keyboard, then it should be interactive; that is, the user should be able to do something to it and produce a change of some kind (for example, activating a link or changing an option).".)

If the heading is a link that can be clicked - that would be the responsibility of the `<a>` tag to provide the focus, so we don't need to solve that here.  

@juanmitriatti Let's just remove the tabindex from the headings. If more than just `h*` tags go through this template, confirm that they provide their own attributes to manage focus. Otherwise, some way to add the tabindex might be necessary - but I doubt it. I think it can just be removed from this template.

2024-10-23 15:46 UTC, mlsamuelson approved these changes

2024-10-23 15:46 UTC, merged